# Name of the workflow
name: Deploy GitHub Pages

# When the workflow will run
on:
  push:
    branches:
      - main # Triggers on push to the main branch

# THIS IS THE CRUCIAL FIX:
# Add permissions for the deployment job to write to your pages.
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true

      # Step 2: GitHub's official action to prepare files
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 3: Action to upload site files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      # Step 4: GitHub's official action to deploy the files
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2