# Name of the workflow
name: Deploy GitHub Pages

# When the workflow will run
on:
  push:
    branches:
      - main # Triggers on push to the main branch

# A workflow run is made up of one or more jobs
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: true # THIS IS THE KEY: It correctly pulls the full LFS files

      # Step 2: This is GitHub's official action to prepare the files for deployment
      - name: Setup Pages
        uses: actions/configure-pages@v3

      # Step 3: This action uploads your site's files as an artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          # Tell it to upload everything from the root directory
          path: '.'

      # Step 4: This is GitHub's official action to deploy the files to your live site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2