name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # This is the corrected step. It now includes 'lfs: true'.
      - name: Checkout with LFS
        uses: actions/checkout@v3
        with:
          lfs: true

      # The old 'run: git lfs pull' step is no longer needed.

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./